name: CI

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ "8.1", "8.2", "8.3" ]

    steps:
    - uses: actions/checkout@v4

    - uses: php-actions/composer@v6
      with:
        php_version: ${{ matrix.php-versions }}

    - uses: php-actions/phpunit@v3
      with:
        php_version: ${{ matrix.php-versions }}
        configuration: phpunit.xml.dist
        bootstrap: vendor/autoload.php

    - uses: php-actions/phpstan@v3
      with:
        path: src/ tests/
        php_version: ${{ matrix.php-versions }}